$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';
$bibtex_use = 2;

# Use xelatex to match editor directive in main.tex
$pdflatex = 'xelatex -interaction=nonstopmode -synctex=1 -file-line-error %O %S';
